[build]
  base = "pcd-website"
  command = "npm run build"
  publish = "dist"

[build.environment]
  DEPLOY_TARGET = "netlify"

[[redirects]]
  from = "/_astro/og-image*"
  to = "/og-image.png"
  status = 301

[[redirects]]
  from = "/_astro/PCD2026_og-image_tinyfied*"
  to = "/og-image.png"
  status = 301

[[headers]]
  for = "/data.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
