blank_issues_enabled: false
contact_links:
  - name: PCD 2026 forum thread
    url: https://discourse.processing.org/t/pcd-worldwide-2026/48081
    about: General questions and discussion for PCD 2026 organizers
