blank_issues_enabled: true
contact_links:
  - name: PCD 2026 forum thread 💬
    url: https://discourse.processing.org/t/pcd-worldwide-2026/48081
    about: Join the discussion, ask questions, and connect with other PCD organizers and participants on the forum.
